"""User-owned reference libraries, copied and hashed before any agent runs.

Plugins are trusted Python supplied by the user, never generated by an agent.
The agents receive text, not tools capable of writing reference files.
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import sys
import re
from pathlib import Path


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def save(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + '.tmp')
    temporary.write_text(json.dumps(data, indent=2, ensure_ascii=False) + '\n')
    temporary.replace(path)


class Library:
    def __init__(self, manifest: Path, workspace: Path):
        self.manifest = manifest.resolve()
        self.root = workspace / 'references'
        self.root.mkdir(parents=True, exist_ok=False)
        spec = json.loads(self.manifest.read_text())
        if spec.get('version') != 1:
            raise ValueError('Unsupported library manifest version')
        self.algorithms = spec['algorithms']
        self.files = {}
        declarations = {f'algorithm:{k}': v['source'] for k, v in self.algorithms.items()}
        self.template_records = {key: ({'source': value, 'description': key, 'tags': []}
                                         if isinstance(value, str) else value)
                                 for key, value in spec['hardware_templates'].items()}
        declarations.update({f'template:{k}': v['source'] for k, v in self.template_records.items()})
        # Test references travel with the selected hardware, and are frozen just
        # like RTL. They are examples to adapt, never executable agent test code.
        for key, record in self.template_records.items():
            for index, source in enumerate(record.get('support_sources', [])):
                declarations[f'support:{key}:{index}'] = source
            for index, test in enumerate(record.get('test_references', [])):
                declarations[f'test:{key}:{index}'] = test['source']
        frozen, hashes = {}, {}
        self._symbols_by_path = {}
        for index, (key, relative) in enumerate(declarations.items()):
            original = (self.manifest.parent / relative).resolve(strict=True)
            if not original.is_file():
                raise ValueError(f'Library entry must be a regular file: {original}')
            copy = frozen.get(original)
            if copy is None:
                copy = self.root / f'{index:03d}{original.suffix}'
                copy.write_bytes(original.read_bytes())
                copy.chmod(0o444)
                frozen[original] = copy
                hashes[original] = digest(copy)
            self.files[key] = {'original': str(original), 'snapshot': str(copy), 'sha256': hashes[original]}
        self.manifest_hash = digest(self.manifest)
        save(workspace / 'library_manifest.json', {'manifest': str(self.manifest),
             'manifest_sha256': self.manifest_hash, 'files': self.files, 'catalog': spec})

    def check(self) -> None:
        if digest(self.manifest) != self.manifest_hash:
            raise RuntimeError('Reference library manifest changed during the run')
        checked = {}
        for value in self.files.values():
            for key in ('original', 'snapshot'):
                path = value[key]
                if path not in checked:
                    checked[path] = digest(Path(path))
                if checked[path] != value['sha256']:
                    raise RuntimeError(f'Reference library changed: {value[key]}')

    def algorithm(self, name: str):
        if name not in self.algorithms:
            raise ValueError(f'Algorithm {name!r} has no trusted executable contract; '
                             f'available: {sorted(self.algorithms)}. No fallback is allowed.')
        path = Path(self.files[f'algorithm:{name}']['snapshot'])
        spec = importlib.util.spec_from_file_location('fast_trusted_' + digest(path)[:16], path)
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return getattr(module, self.algorithms[name]['factory'])()

    def template_index(self) -> list[dict]:
        return [{'id': key, 'description': value.get('description', key),
                 'tags': value.get('tags', []),
                 'support_sources': value.get('support_sources', []),
                 'native_linkable': self.native_linkable(key),
                 'native_library_symbols': self.linked_symbols([key]) if self.native_linkable(key) else {},
                 'provenance': value.get('provenance', {}),
                 'compatibility': value.get('compatibility', ''),
                 'test_references': [{**test, 'sha256': self.files[f'test:{key}:{i}']['sha256']}
                                     for i, test in enumerate(value.get('test_references', []))],
                 'language': value.get('language', 'chisel' if Path(value['source']).suffix == '.scala' else 'verilog'),
                 'sha256': self.files[f'template:{key}']['sha256']}
                for key, value in self.template_records.items()]

    def native_linkable(self, key) -> bool:
        record = self.template_records[key]
        return (Path(record['source']).suffix == '.scala'
                and record.get('language', 'chisel') == 'chisel'
                and record.get('native_linkable', True) is True)

    def templates(self, ids=None) -> dict[str, str]:
        ids = list(self.template_records) if ids is None else list(ids)
        if any(key not in self.template_records for key in ids):
            raise ValueError(f'Unknown hardware reference IDs: {ids}')
        return {key: Path(self.files[f'template:{key}']['snapshot']).read_text() for key in ids}

    def bindings(self, ids) -> list[dict]:
        self.templates(ids)  # validates the IDs; never accepts arbitrary paths
        index = {record['id']: record for record in self.template_index()}
        return [index[key] for key in ids]

    def test_references(self, ids) -> dict:
        self.templates(ids)
        return {key: [{**test, 'sha256': self.files[f'test:{key}:{i}']['sha256'],
                      'code': Path(self.files[f'test:{key}:{i}']['snapshot']).read_text()}
                     for i, test in enumerate(self.template_records[key].get('test_references', []))]
                for key in ids}

    def support_code(self, ids) -> dict:
        self.templates(ids)
        # Shared dependency files appear once even if several bundles were read.
        return {self.files[f'support:{key}:{i}']['sha256']: {
                    'source': source, 'code': Path(self.files[f'support:{key}:{i}']['snapshot']).read_text()}
                for key in ids for i, source in enumerate(self.template_records[key].get('support_sources', []))}

    def linked_sources(self, ids) -> list[Path]:
        self.templates(ids)
        unique = {}
        for key in ids:
            if not self.native_linkable(key):
                raise ValueError(f'{key} is reference-only, not a compatible native Chisel library; '
                                 'use its design as guidance and generate verified modules')
            keys = [f'template:{key}'] + [f'support:{key}:{i}' for i in
                    range(len(self.template_records[key].get('support_sources', [])))]
            for item in keys:
                record = self.files[item]
                path = Path(record['snapshot'])
                if path.suffix != '.scala':
                    raise ValueError('Linked library sources must be Chisel/Scala')
                unique.setdefault(record['sha256'], path)
        return list(unique.values())

    def linked_symbols(self, ids) -> dict:
        classes, packages = set(), set()
        for path in self.linked_sources(ids):
            # Files are frozen; integrity is checked independently by check().
            # Shared full-system bundles must not reread every dependency for
            # every module prompt merely to enumerate native class names.
            if path not in self._symbols_by_path:
                code = re.sub(r'/\*.*?\*/|//[^\n]*', '', path.read_text(), flags=re.S)
                package = re.search(r'^\s*package\s+([\w.]+)', code, re.M)
                prefix = package[1] if package else ''
                names = set(re.findall(r'\bclass\s+(\w+)', code))
                if prefix:
                    names.update(prefix + '.' + name for name in tuple(names))
                self._symbols_by_path[path] = (names, prefix)
            names, prefix = self._symbols_by_path[path]
            classes.update(names)
            if prefix:
                packages.add(prefix)
        return {'classes': sorted(classes), 'packages': sorted(packages)}

    def plan_sources(self, plan, names=None) -> list[Path]:
        ids = list(dict.fromkeys(ref for module in plan.modules if names is None or module.name in names
                                for ref in module.linked_reference_ids))
        return self.linked_sources(ids)

    def check_generated(self, source, module, language):
        from .tools import check_chisel_source, check_source
        if language == 'chisel':
            check_chisel_source(source, module, library_symbols=self.linked_symbols(module.linked_reference_ids))
        else:
            check_source(source, module)

    def check_linked_identity(self, plan, original_manifest, *, snapshot_root=None):
        """Revalidation must rebuild exactly the original linked implementation."""
        ids = {ref for module in plan.modules for ref in module.linked_reference_ids}
        expected = set()
        for ref in ids:
            records = {key: value for key, value in original_manifest['files'].items()
                       if key == f'template:{ref}' or key.startswith(f'support:{ref}:')}
            if f'template:{ref}' not in records:
                raise ValueError(f'Original linked library identity missing: {ref}')
            for record in records.values():
                snapshot = Path(record['snapshot'])
                if snapshot_root is not None:
                    # Archive logs retain their original absolute paths. Rebuild
                    # from the relocated run's frozen files, never that old path.
                    root = Path(snapshot_root).resolve()
                    snapshot = (root / 'references' / snapshot.name).resolve(strict=True)
                    if not snapshot.is_relative_to(root / 'references'):
                        raise ValueError(f'Original linked library integrity failed: {ref}')
                if digest(snapshot) != record['sha256']:
                    raise ValueError(f'Original linked library integrity failed: {ref}')
                expected.add(record['sha256'])
        if expected != {digest(path) for path in self.linked_sources(ids)}:
            raise ValueError('Linked library identity differs from original design')
